//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MBPentity : DbContext
    {
        public MBPentity()
            : base("name=MBPentity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuenta> Cuentas { get; set; }
        public virtual DbSet<Estadistica> Estadisticas { get; set; }
        public virtual DbSet<HistorialPartida> HistorialPartidas { get; set; }
        public virtual DbSet<Jugador> Jugadors { get; set; }
        public virtual DbSet<Moderador> Moderadors { get; set; }
        public virtual DbSet<Nave> Naves { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<Partida> Partidas { get; set; }
        public virtual DbSet<Poder> Poders { get; set; }
        public virtual DbSet<Tablero_Virtual> Tablero_Virtual { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
