//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderador
    {
        public int Usuario_Cuenta_idCuenta { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public string Foto { get; set; }
        public string Local { get; set; }
        public int Pais_idPais { get; set; }
    
        public virtual Pai Pai { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
