//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nave
    {
        public Nave()
        {
            this.Tablero_Virtual = new HashSet<Tablero_Virtual>();
        }
    
        public int idNave { get; set; }
        public int TamanoX { get; set; }
        public int Puntaje { get; set; }
        public string Imagen { get; set; }
        public string Nombre { get; set; }
        public int TamanoY { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Tablero_Virtual> Tablero_Virtual { get; set; }
    }
}
