//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nave()
        {
            this.Partida_Nave = new HashSet<Partida_Nave>();
            this.Tablero_Virtual_1 = new HashSet<Tablero_Virtual_1>();
            this.Tablero_Virtual_2 = new HashSet<Tablero_Virtual_2>();
        }
    
        public int idNave { get; set; }
        public int TamanoX { get; set; }
        public int Puntaje { get; set; }
        public string Imagen { get; set; }
        public string Nombre { get; set; }
        public int TamanoY { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partida_Nave> Partida_Nave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tablero_Virtual_1> Tablero_Virtual_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tablero_Virtual_2> Tablero_Virtual_2 { get; set; }
    }
}
