//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida_Nave
    {
        public int Partida_idPartida { get; set; }
        public int Nave_idNave { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Nave Nave { get; set; }
        public virtual Partida Partida { get; set; }
    }
}
