//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partida()
        {
            this.Partida_Nave = new HashSet<Partida_Nave>();
        }
    
        public int idPartida { get; set; }
        public bool Publico { get; set; }
        public int DisparosJugador1 { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Jugador1_idCuenta { get; set; }
        public int Jugador2_idCuenta { get; set; }
        public int Tamano { get; set; }
        public int Estado { get; set; }
        public int DisparosJugador2 { get; set; }
        public bool TurnoActual { get; set; }
        public int DisparosRestantes { get; set; }
        public int PuntajeJugador1 { get; set; }
        public int PuntajeJugador2 { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partida_Nave> Partida_Nave { get; set; }
    }
}
