//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poder()
        {
            this.Jugador = new HashSet<Jugador>();
        }
    
        public int idPoder { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Experiencia { get; set; }
        public Nullable<int> Victorias { get; set; }
        public Nullable<int> Puntos { get; set; }
        public Nullable<int> Derrotas { get; set; }
        public Nullable<int> Ranking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugador> Jugador { get; set; }
    }
}
