//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poder
    {
        public Poder()
        {
            this.Jugador = new HashSet<Jugador>();
        }
    
        public int idPoder { get; set; }
        public string Nombre { get; set; }
        public int Experiencia { get; set; }
        public int Victorias { get; set; }
        public int Puntos { get; set; }
        public int Derrotas { get; set; }
    
        public virtual ICollection<Jugador> Jugador { get; set; }
    }
}
