//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablero_Virtual
    {
        public int Id { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public int NumeroNave { get; set; }
        public Nullable<int> Poder { get; set; }
        public string Destruido { get; set; }
        public int Nave_idNave { get; set; }
        public int Partida_idPartida { get; set; }
    
        public virtual Nave Nave { get; set; }
    }
}
